import { definePrompt } from 'cz-git';

export default definePrompt({
  alias: { fd: 'docs: fix typos' },
  messages: {
    type: "Select the type of change that you're committing:",
    scope: 'Select the scope of this change:',
    subject: 'Write a commit description:\n',
    body: 'Provide a longer description of the change (optional). Use "|" to break new line:\n',
    confirmCommit: 'Are you sure you want to proceed with the commit above?',
  },
  types: [
    {
      value: 'feat',
      name: 'feat:     A new feature',
      emoji: '✨',
    },
    {
      value: 'fix',
      name: 'fix:      A bug fix',
      emoji: '🐛',
    },
    {
      value: 'chore',
      name: "chore:    Other changes that don't modify src or test files",
      emoji: '🔨',
    },
    {
      value: 'test',
      name: 'test:     Adding missing tests or correcting existing tests',
      emoji: '✅',
    },
    {
      value: 'docs',
      name: 'docs:     Documentation only changes',
      emoji: '📝',
    },
    {
      value: 'ci',
      name: 'ci:       Changes to our CI configuration files and scripts',
      emoji: '🎡',
    },
    {
      value: 'style',
      name: 'style:    Changes that do not affect the meaning of the code',
      emoji: '💄',
    },
    {
      value: 'refactor',
      name: 'refactor: A code change that neither fixes a bug nor adds a feature',
      emoji: '♻️',
    },
    {
      value: 'perf',
      name: 'perf:     A code change that improves performance',
      emoji: '⚡',
    },
    {
      value: 'revert',
      name: 'revert:   Reverts a previous commit',
      emoji: '⏪',
    },
  ],
  scopes: [
    'app',
    'assets',
    'components',
    'context',
    'hooks',
    'libs',
    'pages',
    'routes',
    'types',
    'utils',
    'ci',
    'deps',
    'docs',
    'lint',
    'test',
  ],
  breaklineChar: '|',
  useEmoji: false,
  emojiAlign: 'left',
  allowCustomScopes: false,
  allowEmptyScopes: false,
  customScopesAlign: 'bottom',
  customScopesAlias: 'custom',
  emptyScopesAlias: 'empty',
  upperCaseSubject: false,
  markBreakingChangeMode: false,
  allowBreakingChanges: ['feat', 'fix'],
  breaklineNumber: 100,
  skipQuestions: ['breaking', 'footer', 'footerPrefix', 'confirmCommit'],
  customIssuePrefixAlign: 'top',
  emptyIssuePrefixAlias: 'skip',
  customIssuePrefixAlias: 'custom',
  confirmColorize: true,
  maxHeaderLength: Infinity,
  maxSubjectLength: 100,
  minSubjectLength: 0,
});
